trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Installation de Node.js (nécessaire pour certains outils de validation HTML/CSS)
- script: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
  displayName: 'Install Node.js'

# Installation de HTMLHint, un validateur HTML
- script: |
    npm install -g htmlhint
  displayName: 'Install HTMLHint'

# Validation du HTML
- script: |
    htmlhint '**/*.html'
  displayName: 'Validate HTML'

# pour afficher le résultat de la validation (Optionnel)
- script: |
    htmlhint '**/*.html' --format html > htmlhint-report.html
  displayName: 'Generate HTMLHint Report'

# Déploiement sur GitHub Pages (automatisé par mon GitHub donc pas besoin de script )
- script: |
    echo "Déploiement géré par mon GitHub Pages"
  displayName: 'Deployment Handled by GitHub Pages'
